from __future__ import annotations
import json
import pprint
from pathlib import Path

from .config import Config

# The exact defaults YACHIYO's infer.py uses (default_tracking_parameters),
# plus replace_value consumed by mcpt.replace_negative_value_by_wcoordinate.
TRACKING_PARAM_DEFAULTS: dict = {
    "epsilon_scpt": 0.10,
    "time_period": 3,
    "epsilon_mcpt": 0.37,
    "short_track_th": 120,
    "keypoint_condition_th": 1,
    "replace_similarity_by_wcoordinate": True,
    "distance_type": "min",
    "distance_th": 10,
    "sim_th": 0.85,
    "delete_gid_th": 5000,
    "replace_value": -10,
}

# Only these keys are allowed in the config tracking_params block.
ALLOWED_KEYS = set(TRACKING_PARAM_DEFAULTS)

# When mct.hard_world_gate is on, push replace_value far negative so any pair
# beyond distance_th can never be merged (hard cannot-link).
HARD_GATE_REPLACE_VALUE = -1e9


def build_tracking_params(cfg: Config) -> dict:
    """Merge config overrides onto the verified YACHIYO defaults. Never empty."""
    params = dict(TRACKING_PARAM_DEFAULTS)
    for k, v in cfg.tracking_params.items():
        if k not in ALLOWED_KEYS:
            raise ValueError(
                f"unknown tracking_params key {k!r}; allowed: {sorted(ALLOWED_KEYS)}"
            )
        params[k] = v
    if cfg.mct.hard_world_gate:
        params["replace_value"] = HARD_GATE_REPLACE_VALUE
        params["replace_similarity_by_wcoordinate"] = True
    return params


def write_parameters_per_scene(cfg: Config, yachiyo_root: Path, scene_int: int) -> Path:
    """Write tracking/config/parameters_per_scene.py so infer.py reads our params.

    infer.py does: parameters_per_scene[scene]["tracking_parameters"].
    """
    params = build_tracking_params(cfg)
    if not params:
        raise RuntimeError("build_tracking_params produced an empty dict")
    dst = Path(yachiyo_root) / "tracking" / "config" / "parameters_per_scene.py"
    dst.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "# AUTO-GENERATED by aic24_nvidia.tracking_params — do not edit by hand.\n"
        f"parameters_per_scene = {{{int(scene_int)}: {{'tracking_parameters': "
        f"{pprint.pformat(params)}}}}}\n"
    )
    dst.write_text(body)
    return dst
