#!/usr/bin/env bash
# Verify that the vendored upstream patches are applied in external/.
#
# Method: each patch only touches specific files, so we ask git whether those
# files differ from the pinned-clean checkout. A clean (un-patched) file means
# the patch was lost (e.g. a re-clone without applying patches/) — we fail.
# This is text-independent (no fragile string matching) with a human-readable
# grep sentinel as a backstop.
#
# Exit 0 = all patches present; non-zero = something is missing.

set -uo pipefail

cd "$(dirname "$0")/.."
EXTERNAL="$(pwd)/external"
fail=0

YACHIYO="$EXTERNAL/AIC24_Track1_YACHIYO_RIIPS"
TRACKEVAL="$EXTERNAL/TrackEval"

# YACHIYO: the static patches live ONLY in these two files. (The other modified
# tracked files — parameters_per_scene.py, scene_2_camera_id_file.json — are
# generated by our pipeline at runtime, not patches, so they are excluded.)
if [ -d "$YACHIYO" ]; then
    if git -C "$YACHIYO" diff --quiet -- tracking/infer.py tracking/src/mcpt.py; then
        echo "FAIL: YACHIYO patches missing (infer.py / mcpt.py match pristine upstream)"
        fail=1
    else
        echo "ok:   YACHIYO patches present (infer.py + mcpt.py)"
    fi
    grep -q 'set_start_method' "$YACHIYO/tracking/infer.py" 2>/dev/null \
        || { echo "FAIL: infer.py multiprocessing fork patch missing"; fail=1; }
else
    echo "WARN: $YACHIYO not present (run bootstrap_external.sh first)"
    fail=1
fi

# TrackEval: the np.float/int/bool -> builtins patch touches ~20 files; checking
# one representative file is sufficient.
if [ -d "$TRACKEVAL" ]; then
    if git -C "$TRACKEVAL" diff --quiet -- trackeval/metrics/hota.py; then
        echo "FAIL: TrackEval patches missing (hota.py matches pristine upstream)"
        fail=1
    else
        echo "ok:   TrackEval patches present (np.float -> builtins)"
    fi
else
    echo "WARN: $TRACKEVAL not present (run bootstrap_external.sh first)"
    fail=1
fi

if [ "$fail" -eq 0 ]; then
    echo "All upstream patches verified."
fi
exit "$fail"
